### ISSUE TITLE
Monotonic ID generation randomness increment variability

### ISSUE THREAD

**Issue by lukevp** [kyoheiu/ulideno#1]
The randomness increment code specifies a RANDOM_MAX and doesn't let the random value exceed this value.  However, this means that in a given millisecond, there are more or fewer available IDs depending on where in the range of random values was generated (eg. if the range of random values was 1 - 1000, and you generated the first ID that millisecond at 999, you would only have 1 more ID available before running out).

My suggestion is that the random incrementer should just wrap around to 0 in this case.  There's not really a need to worry about collision unless 80 bits-worth of IDs are requested in a given millisecond, in which case we'd have an issue regardless of the algorithm because the whole space would already be allocated.

**Comment by kyoheiu** [comment]
Thank you, fixed in v0.2.1.
